"""
rclone_stats.py - Rclone Remote Control (RC) telemetry and statistics consumer.

Polls the `/core/stats` HTTP endpoint at 1-second intervals using Basic Auth
with ephemeral credentials generated by rclone_daemon. Computes transfer speeds (MB/s),
remaining time ETA in HH:MM:SS, and descriptive status text.
"""

import base64
import json
import logging
import time
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from PySide6.QtCore import QThread, Signal

from rclone_daemon import RCCredentials

logger = logging.getLogger(__name__)


@dataclass
class StatsData:
    """Represents a telemetry snapshot from the Rclone RC API."""
    is_online: bool
    speed_bytes_per_sec: float = 0.0
    speed_mb_s: float = 0.0
    speed_str: str = "0.00 MB/s"
    eta_seconds: Optional[int] = None
    eta_str: str = "--:--:--"
    transfers_count: int = 0
    total_bytes_transferred: int = 0
    total_bytes_str: str = "0 B"
    errors_count: int = 0
    status_text: str = "Disconnected"
    active_transfers: List[Dict[str, Any]] = field(default_factory=list)
    raw_data: Dict[str, Any] = field(default_factory=dict)


def format_bytes(num_bytes: int) -> str:
    """
    Formats a raw byte count into human-readable units (B, KB, MB, GB, TB).

    Args:
        num_bytes: The number of bytes.

    Returns:
        str: Human-readable string.
    """
    if num_bytes < 0:
        return "0 B"
    for unit in ("B", "KB", "MB", "GB", "TB", "PB"):
        if num_bytes < 1024.0:
            return f"{num_bytes:.2f} {unit}" if unit != "B" else f"{int(num_bytes)} B"
        num_bytes /= 1024.0
    return f"{num_bytes:.2f} PB"


def format_eta(eta_seconds: Optional[int]) -> str:
    """
    Formats an ETA in seconds into HH:MM:SS format.

    Args:
        eta_seconds: Estimated remaining seconds, or None.

    Returns:
        str: Formatted ETA string (e.g., '01:15:30' or '--:--:--').
    """
    if eta_seconds is None or eta_seconds < 0:
        return "--:--:--"

    hours = eta_seconds // 3600
    minutes = (eta_seconds % 3600) // 60
    seconds = eta_seconds % 60
    return f"{hours:02d}:{minutes:02d}:{seconds:02d}"


def fetch_rclone_stats(creds: RCCredentials, timeout: float = 1.5) -> StatsData:
    """
    Executes a single HTTP POST query to `http://<host>:<port>/core/stats`
    using HTTP Basic Auth.

    Args:
        creds: In-memory credentials for the Rclone RC API.
        timeout: Request timeout in seconds.

    Returns:
        StatsData: Parsed telemetry snapshot.
    """
    endpoint = f"{creds.url}/core/stats"
    auth_str = f"{creds.user}:{creds.password}"
    b64_auth = base64.b64encode(auth_str.encode("utf-8")).decode("ascii")

    req = urllib.request.Request(
        url=endpoint,
        data=b"{}",
        headers={
            "Authorization": f"Basic {b64_auth}",
            "Content-Type": "application/json",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=timeout) as response:
            if response.status == 200:
                raw_json = response.read().decode("utf-8")
                data: Dict[str, Any] = json.loads(raw_json)

                speed_bytes = float(data.get("speed", 0.0))
                speed_mb_s = speed_bytes / (1024.0 * 1024.0)
                speed_str = f"{speed_mb_s:.2f} MB/s"

                raw_eta = data.get("eta")
                eta_seconds = int(raw_eta) if raw_eta is not None else None
                eta_str = format_eta(eta_seconds)

                transfers = int(data.get("transfers", 0))
                active_transfers = data.get("transferring", [])
                total_bytes = int(data.get("bytes", 0))
                errors = int(data.get("errors", 0))

                # Determine high-level descriptive status
                if transfers > 0 or len(active_transfers) > 0:
                    status_text = f"Syncing ({len(active_transfers)} active) • {speed_str} • ETA {eta_str}"
                elif errors > 0:
                    status_text = f"Idle with {errors} error(s)"
                else:
                    status_text = "Synchronized / Idle"

                return StatsData(
                    is_online=True,
                    speed_bytes_per_sec=speed_bytes,
                    speed_mb_s=speed_mb_s,
                    speed_str=speed_str,
                    eta_seconds=eta_seconds,
                    eta_str=eta_str,
                    transfers_count=transfers,
                    total_bytes_transferred=total_bytes,
                    total_bytes_str=format_bytes(total_bytes),
                    errors_count=errors,
                    status_text=status_text,
                    active_transfers=active_transfers,
                    raw_data=data,
                )

    except urllib.error.HTTPError as http_err:
        logger.debug("HTTP error polling rclone stats: %s", http_err)
    except urllib.error.URLError as url_err:
        logger.debug("Connection error polling rclone stats: %s", url_err)
    except Exception as exc:
        logger.debug("Unexpected error polling rclone stats: %s", exc)

    return StatsData(is_online=False, status_text="Drive not connected")


class RcloneStatsPoller(QThread):
    """
    Dedicated background worker thread that polls Rclone RC `/core/stats`
    every 1 second and emits parsed statistics signals.
    """

    stats_updated = Signal(object)  # Emits StatsData instance
    connection_lost = Signal()

    def __init__(
        self,
        credentials: RCCredentials,
        poll_interval: float = 1.0,
        parent: Optional[Any] = None,
    ) -> None:
        super().__init__(parent)
        self.credentials = credentials
        self.poll_interval = poll_interval
        self._running = False

    def run(self) -> None:
        """Main polling loop running once per second."""
        self._running = True
        logger.info("Started stats polling thread for %s", self.credentials.url)

        was_online = False
        while self._running:
            stats = fetch_rclone_stats(self.credentials, timeout=1.5)

            if stats.is_online:
                was_online = True
                self.stats_updated.emit(stats)
            else:
                if was_online:
                    self.connection_lost.emit()
                    was_online = False
                self.stats_updated.emit(stats)

            # Sleep in small increments for responsive thread termination
            steps = int(self.poll_interval / 0.1)
            for _ in range(max(1, steps)):
                if not self._running:
                    break
                time.sleep(0.1)

        logger.info("Stopped stats polling thread.")

    def stop(self) -> None:
        """Stops the polling loop and waits for thread termination."""
        self._running = False
        if hasattr(self, "wait"):
            self.wait(timeout=2000)
